### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by cballenar** [senchalabs/cssbeautify#14]
This is not really an issue, just a suggestion.
I think it'd be cool to offer the option to group CSS properties, i.e.:

``` css
.class {
    width: 10px; height: 10px;
    margin: 0; padding: 0;
    top: 108px; left: 231px;
}
```
