### ISSUE TITLE
Add Support for Sass

### ISSUE THREAD

**Issue by wemakeweb** [senchalabs/cssbeautify#19]
Is it possible to add support for this? Especially the scss nesting should not result in invalid css after running through cssbeautify. Im not sure if its interesting for others and worth the time implementing it.

Currently:

``` css
.item{
  width: 185px;
  cursor:pointer;

  &:active{
    border: 1px solid #6692BB;  
  }
}
```

results in:

``` css
.item {
    width: 185px;
    cursor: pointer;
    &: active{
    border: 1px solid #6692BB;
}
}
```
