### ISSUE TITLE
Order all properties alphabetically?

### ISSUE THREAD

**Issue by fortes** [senchalabs/cssbeautify#38]
Would it be possible to support re-ordering CSS declarations to be in alphabetical order? E.g.:

``` css
body {
  font-family: Georgia;
  color: blue;
  text-decoration: underline;
}
```

Would become:

``` css
body {
  color: blue;
  font-family: Georgia;
  text-decoration: underline;
}
```
