### ISSUE TITLE
This CSS breaks the parser

### ISSUE THREAD

**Issue by gbell12** [senchalabs/cssbeautify#44]
```
a#googleplus:hover,a#googleplus:active {
  background:transparent url(img/googleplus_a.png) no-repeat
}

/* Fixed layout for home page - don't*/
#home-top {
  height:336px;
  margin-bottom:100px
}
```

Test at http://www.senchalabs.org/cssbeautify/ and you'll see the CSS below the comments does not get changed.  It's the apostrophe in "don't" that's doing it.

**Comment by kwoodfriend** [comment]
I also ran into this issue. The problem is the parser is choking on the fact that there's either a single or double quote within a comment block, without a corresponding closing quote. 

The following will not be formatted properly:

```css
/* Testing failure from ' mark */  

p{color:red}
```

However, this works, with 2 single quotes

```css
/* Testing failure from '' mark */  

p{color:red}
```
