### ISSUE TITLE
@media query bug

### ISSUE THREAD

**Issue by rkhat** [senchalabs/cssbeautify#46]
The beautifier adds a semicolon inside the media query at the end. According to w3 css-validator, this is an error. Example:
```css
@media (max-width: 767px) {
  h1 {
    font-size: 32px;
  }
}
```
Your beautifier will give:
```css
@media (max-width: 767px) {
  h1 {
    font-size: 32px;
  };    /* The semicolon here will give an error. */
}
```
